### ISSUE TITLE
[-Dscala.version=2.11.2] [-Dsbt.version=0.13.7]" does not work

### ISSUE THREAD

**Issue by mkotsbak** [ajozwik/mvn2sbt#3]
It seems like they are added as normal arguments, then giving:

[error] (run-main-0) java.lang.IllegalArgumentException: Use <rootDirWithMavenProject> [<outputDir>]

as it now has 3 or 4 arguments.

Workaround:

Run it as
1.  sbt -Dscala.version=2.11.7 -Dsbt.version=0.13.8
2. converter/run mavenDir

**Comment by ajozwik** [comment]
Parameters added as `[..]` are optional and should be added without brackets []. It is standard linux notations for optional parameters in command.

**Comment by mkotsbak** [comment]
I's not the brackets that is the problem, but these checks that fails when the number of arguments increases by the "-D" arguments:

    val out = if (args.length == 1) {
      args(0)
    } else if (args.length == 2) {
